name: personal_admin::delegator
class_name: Delegator
llm_params:
  llm_provider: "openai"
  engine: "gpt-5-mini"
  model_tier: "mini"

allowed_tools: []
except_tools: []
allowed_nodes: all

user_context_items: []
system_context_items: []
