"""Labeled task-delegation test cases for master_room::switchboard.

Each case has:
  id          — short stable identifier (used in test output)
  task        — what the chat_gate would pass as `switchboard_task`
  information — what it would pass as `switchboard_information` (often "")
  expected    — the manager I believe is "correct" per the switchboard system prompt
  accept_also — additional acceptable delegates (for genuinely ambiguous cases)
  category    — bucket the case is testing (for the per-category breakdown)
  notes       — why this is the expected answer (helps grading my labels)

These labels are MY READING of the switchboard system prompt. Grade them —
corrections feed the next batch.
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import Tuple


@dataclass(frozen=True)
class Case:
    id: str
    task: str
    information: str
    expected: str
    accept_also: Tuple[str, ...] = ()
    category: str = ""
    notes: str = ""


CASES: Tuple[Case, ...] = (
    # =========================================================================
    # one_shot_tool_runner — single create / single quick-read / weather
    # =========================================================================
    Case("weather_irvine",
         "What's the weather in Irvine?", "",
         "one_shot_tool_runner",
         category="one_shot",
         notes="Weather rule (strict)."),
    Case("weather_cupertino",
         "What's the weather like in Cupertino tomorrow?", "",
         "one_shot_tool_runner",
         category="one_shot",
         notes="Weather rule (strict)."),
    Case("ac_70",
         "Set the AC to 70.", "",
         "one_shot_tool_runner", accept_also=("devices_manager",),
         category="one_shot",
         notes="Single smart-home action with clear intent."),
    Case("lights_off_kitchen",
         "Turn off the kitchen lights.", "",
         "one_shot_tool_runner", accept_also=("devices_manager",),
         category="one_shot",
         notes="Single smart-home action."),
    Case("create_reminder_trash",
         "Add a reminder to take out the trash tomorrow at 8pm.", "",
         "one_shot_tool_runner",
         category="one_shot",
         notes="Single create of ONE reminder."),
    Case("create_calendar_dentist",
         "Create a calendar event called 'Dentist' on Friday at 10am.", "",
         "one_shot_tool_runner",
         category="one_shot",
         notes="Single create of ONE calendar event."),
    Case("email_check_simple",
         "Any new emails today?", "",
         "one_shot_tool_runner",
         category="one_shot",
         notes="Simple email check → get_important_emails."),
    Case("email_count",
         "How many emails do I have in my inbox?", "",
         "one_shot_tool_runner", accept_also=("personal_admin_manager",),
         category="one_shot",
         notes="Simple email read; borderline if there's no count tool."),
    Case("peek_link_generic",
         "Look at this link and tell me what it says: https://example.com/article", "",
         "one_shot_tool_runner",
         category="one_shot",
         notes="Single-link quick read."),
    Case("peek_link_hn",
         "Peek at this URL: https://news.ycombinator.com/item?id=42", "",
         "one_shot_tool_runner",
         category="one_shot",
         notes="Peek URL rule."),
    Case("summarize_wiki",
         "What does this Wikipedia page say about quantum entanglement: https://en.wikipedia.org/wiki/Quantum_entanglement", "",
         "one_shot_tool_runner", accept_also=("web_manager",),
         category="one_shot",
         notes="Single-link summarize; borderline one_shot vs web_manager."),
    Case("ring_status",
         "Check the Ring camera and tell me if anyone's at the door.", "",
         "one_shot_tool_runner", accept_also=("devices_manager",),
         category="one_shot",
         notes="'Ring quick status' is explicit one_shot in prompt."),

    # =========================================================================
    # personal_admin_manager — complex email/calendar/todo, find+modify, sends
    # =========================================================================
    Case("email_find_dentist",
         "Find the email Katy sent me about the dentist appointment last week.", "",
         "personal_admin_manager", accept_also=("one_shot_tool_runner",),
         category="personal_admin",
         notes="Email search beyond get_important_emails — closer to personal_admin."),
    Case("calendar_reschedule",
         "Reschedule my 3pm meeting on Thursday to 4pm.", "",
         "personal_admin_manager",
         category="personal_admin",
         notes="Find calendar event + modify."),
    Case("trash_spam",
         "Trash all the unread spam emails from senders I've already blocked.", "",
         "personal_admin_manager",
         category="personal_admin",
         notes="Find + delete (one_shot excludes deletes)."),
    Case("delete_recurring_yoga",
         "Delete the recurring yoga event from my calendar.", "",
         "personal_admin_manager",
         category="personal_admin",
         notes="Find + delete recurring event."),
    Case("email_phil_trip",
         "Email Phil and ask him how his trip to Connecticut was.", "",
         "personal_admin_manager",
         category="personal_admin",
         notes="Send email (Phil is not the chat user)."),
    Case("multi_reminders",
         "Set 3 reminders: 9am stretch, 1pm walk, 5pm meds.", "",
         "personal_admin_manager",
         category="personal_admin",
         notes="Multiple creates — explicit prompt rule says NOT one_shot."),
    Case("email_katy_pizza",
         "Send Katy an email asking if she wants pizza tonight.", "",
         "personal_admin_manager",
         category="personal_admin",
         notes="Send email; Katy isn't the chat user."),
    Case("reply_peter_meet",
         "Find Peter's last email and reply that I'll meet him at 5.", "",
         "personal_admin_manager",
         category="personal_admin",
         notes="Find + reply."),
    Case("inbox_review_week",
         "Go through my unread emails from this week and summarize the important ones.", "",
         "personal_admin_manager",
         category="personal_admin",
         notes="Multi-step email triage — too complex for one_shot (graded by user 2026-05-17)."),

    # =========================================================================
    # web_manager — passive web reads, distance, service lookups
    # =========================================================================
    Case("dist_lax",
         "How far is it from my house to LAX?", "",
         "web_manager",
         category="web",
         notes="Distance/routing rule."),
    Case("search_thai",
         "Search the web for the best Thai place in Irvine.", "",
         "web_manager",
         category="web",
         notes="Search engine query."),
    Case("cnn_latest",
         "What's the latest news from CNN?", "",
         "web_manager", accept_also=("playwright_manager",),
         category="web",
         notes="Passive web read; CNN front page is mostly static."),
    Case("reddit_rust",
         "Search Reddit for r/programming threads about Rust this week.", "",
         "web_manager", accept_also=("playwright_manager",),
         category="web",
         notes="Reddit is browsable without login."),
    Case("hn_top",
         "Read the top story on Hacker News.", "",
         "web_manager", accept_also=("one_shot_tool_runner",),
         category="web",
         notes="Passive read; HN works without a live browser."),
    Case("github_stats",
         "Check the stats on my GitHub page.", "",
         "emi_team_manager", accept_also=("web_manager", "playwright_manager"),
         category="web",
         notes="THE FAILURE CASE that motivated this test. 'My GitHub page' needs username lookup (KG) + scrape. web_manager has no user-fact tools, so cross-domain → emi_team. web_manager would have to guess the handle."),
    Case("github_trending",
         "Check the trending repos on GitHub today.", "",
         "web_manager", accept_also=("playwright_manager",),
         category="web",
         notes="Public web read."),
    Case("bluesky_public_profile",
         "What's @anthropic posting about on Bluesky today?", "",
         "web_manager", accept_also=("playwright_manager",),
         category="web",
         notes="Public Bluesky profile is readable without login."),
    Case("reddit_top_programming",
         "What are the top posts on r/programming today?", "",
         "web_manager",
         category="web",
         notes="Public reddit read."),

    # =========================================================================
    # playwright_manager — live browser, login required, JS-heavy
    # =========================================================================
    Case("doordash_pizza",
         "Open DoorDash and order a large pepperoni pizza.", "",
         "playwright_manager",
         category="playwright",
         notes="DoorDash explicitly listed in prompt; needs live browser."),
    Case("schwab_balance",
         "Log into my Schwab account and check my balance.", "",
         "playwright_manager",
         category="playwright",
         notes="Login required → playwright."),
    Case("bluesky_post",
         "Go to my Bluesky page and post 'Good morning'.", "",
         "playwright_manager",
         category="playwright",
         notes="'Go to <site> and do X' + authenticated post action."),
    Case("gform_fill",
         "Open the browser and fill out this Google Form: https://forms.gle/abc123", "",
         "playwright_manager",
         category="playwright",
         notes="Explicit 'open the browser' + form fill."),
    Case("twitter_like",
         "Navigate to twitter.com and like the latest post from @anthropic.", "",
         "playwright_manager",
         category="playwright",
         notes="Navigate + click action."),
    Case("bluesky_my_posts",
         "Get my latest 5 posts from Bluesky.", "",
         "emi_team_manager", accept_also=("playwright_manager", "web_manager"),
         category="emi_team",
         notes="'My posts' needs handle lookup (KG) + Bluesky fetch. Cross-domain → emi_team. Bluesky profiles ARE publicly readable, so web_manager could work if the handle were known."),

    # =========================================================================
    # emi_team_manager — cross-domain / pods / gdocs / unclear
    # =========================================================================
    Case("email_photo_bonnie",
         "Send the photo of Bonnie I took yesterday to Katy.", "",
         "emi_team_manager",
         category="emi_team",
         notes="File→email EXCEPTION: bash mints pod, personal_admin sends."),
    Case("recipe_to_phil",
         "Find me a recipe for chicken curry and send the URL to Phil.", "",
         "emi_team_manager",
         category="emi_team",
         notes="Cross-domain: web search + send email."),
    Case("pdf_fill_send",
         "Download the PDF from Peter's last email, fill it out, and send it back.", "",
         "emi_team_manager",
         category="emi_team",
         notes="Cross-domain: email read + form fill + email send."),
    Case("spreadsheet_to_susie",
         "Take the spreadsheet from ~/Documents/budget.xlsx and email it to Susie.", "",
         "emi_team_manager",
         category="emi_team",
         notes="File→email exception; bash+admin orchestration."),
    Case("gdoc_project_plan",
         "Create a new Google Doc called 'Project Plan' and write a one-page outline of my EmiOS project.", "",
         "emi_team_manager",
         category="emi_team",
         notes="gdoc create + multi-step composition → emi_team (per user rule: gdoc work needs orchestration)."),
    Case("gdoc_journal_append",
         "Open my 'Daily Journal' Google Doc and append today's entry: 'Worked on switchboard tests.'", "",
         "emi_team_manager",
         category="emi_team",
         notes="gdoc find + append. ONLY emi_team can handle gdoc multi-step (graded by user 2026-05-17)."),
    Case("email_landlord_to_calendar",
         "Read the email from my landlord about lease renewal and add the key dates to my calendar.", "",
         "personal_admin_manager",
         category="personal_admin",
         notes="Email + calendar are both personal_admin's domain — NOT emi_team (graded by user 2026-05-17)."),
    Case("gdoc_github_summary",
         "Make a Google Doc summarizing my GitHub activity this week.", "",
         "emi_team_manager",
         category="emi_team",
         notes="Web read + gdoc write — cross-domain."),
    Case("email_agenda_to_todo",
         "Get the agenda items from Peter's email and add them to my todo list.", "",
         "personal_admin_manager",
         category="personal_admin",
         notes="Email + todo are both personal_admin's domain — NOT emi_team (graded by user 2026-05-17)."),

    # =========================================================================
    # devices_manager — multi-step or planned smart-home
    # =========================================================================
    Case("lights_off_ac_75",
         "Turn off all the lights and set the AC to 75.", "",
         "devices_manager",
         category="devices",
         notes="Two-action smart home → devices_manager (multi-step)."),
    Case("thermo_porch_schedule",
         "Lower the upstairs thermostat to 68 and turn on the porch light at 7pm.", "",
         "devices_manager",
         category="devices",
         notes="Multi-step + scheduling."),

    # =========================================================================
    # bash_manager — filesystem reads only
    # =========================================================================
    Case("ls_documents",
         "List the files in my Documents folder.", "",
         "bash_manager",
         category="bash",
         notes="List folder."),
    Case("find_taxes_file",
         "Find a file called 'taxes_2025.pdf' somewhere on my disk.", "",
         "bash_manager",
         category="bash",
         notes="Find by name."),
    Case("cat_notes",
         "Show me the contents of ~/projects/notes.txt.", "",
         "bash_manager",
         category="bash",
         notes="Show text file contents."),
    Case("ls_downloads",
         "What's in my Downloads folder?", "",
         "bash_manager",
         category="bash",
         notes="List folder."),

    # =========================================================================
    # create_dayflow_ticket — notify/ask the user; user is source of answer
    # =========================================================================
    Case("ask_user_pizza_self",
         "Ask me whether I want pizza tonight.", "",
         "create_dayflow_ticket",
         category="ticket",
         notes="User is the source of the answer."),
    Case("notify_leak_ask_plumber",
         "Notify Jukka about the leak in the kitchen and ask whether to call the plumber.", "",
         "create_dayflow_ticket",
         category="ticket",
         notes="Notify+ask (user knows the answer) — explicit rule says still ticket."),
    Case("checkin_meeting",
         "Check in with me later about how the meeting went.", "",
         "create_dayflow_ticket",
         category="ticket",
         notes="Asking the user later."),

    # =========================================================================
    # run_task — explicit "run/execute"
    # =========================================================================
    Case("run_morning_briefing",
         "Run task morning_briefing.", "",
         "run_task",
         category="run_task",
         notes="Explicit 'Run task X'."),
    Case("execute_weekly_review",
         "Execute task weekly_review.", "",
         "run_task",
         category="run_task",
         notes="Explicit 'Execute task X'."),
    Case("run_job_kg",
         "Run job nightly_kg_maintenance.", "",
         "run_task",
         category="run_task",
         notes="Explicit 'Run job X'."),

    # =========================================================================
    # task_compile_manager — explicit "compile" of a task spec
    # =========================================================================
    Case("compile_timesheets",
         "Compile the timesheets task spec.", "",
         "task_compile_manager",
         category="task_compile",
         notes="Explicit 'compile' intent for task spec."),
    Case("compile_morning_briefing",
         "Compile the morning_briefing task.", "",
         "task_compile_manager",
         category="task_compile",
         notes="Explicit 'compile' intent."),

    # =========================================================================
    # tricky / edge cases — known ambiguities
    # =========================================================================
    Case("ask_katy_pizza",
         "Ask Katy whether she wants pizza tonight.", "",
         "personal_admin_manager",
         accept_also=("emi_team_manager", "create_dayflow_ticket"),
         category="tricky",
         notes="Genuinely ambiguous (graded by user 2026-05-17): (a) send email to Katy now, OR (b) deferred ticket — ask user at dinner-time whether Katy wants pizza. Either reading is defensible."),
    Case("flights_nyc_ask",
         "Find me cheap flights to NYC and ask if I want to book one.", "",
         "web_manager", accept_also=("emi_team_manager", "playwright_manager"),
         category="tricky",
         notes="Research+report; trailing 'ask if I want to book' is framing, not the primary verb."),
    Case("yoga_top_pick",
         "Search for the best yoga studios near me and tell me your top pick.", "",
         "web_manager",
         category="tricky",
         notes="Research+report. Primary verb is search."),
    Case("compile_gift_ideas",
         "Compile a list of holiday gift ideas.", "",
         "web_manager", accept_also=("emi_team_manager",),
         category="tricky",
         notes="'Compile' here is colloquial — NOT task-spec compile."),

    # =========================================================================
    # BATCH 2 (added 2026-05-17 after user grading of batch 1)
    # Probes the patterns batch 1 revealed:
    #   - gdoc ALWAYS goes to emi_team
    #   - personal_admin covers email+calendar+todo+reminder in any combo
    #   - emi_team is for stepping OUTSIDE those four admin domains
    #   - "ask <X>" is ambiguous; X=user → ticket, X=other person → email
    # =========================================================================

    # ---- gdoc probes: all should route to emi_team_manager ----
    Case("gdoc_read_q3_notes",
         "Read my 'Q3 Notes' Google Doc and tell me the action items.", "",
         "emi_team_manager",
         category="emi_team",
         notes="gdoc find + read = multi-step → emi_team."),
    Case("gdoc_replace_text",
         "Replace 'TBD' with '2026-05-20' in my 'Sprint Plan' Google Doc.", "",
         "emi_team_manager",
         category="emi_team",
         notes="gdoc find + edit = multi-step → emi_team."),
    Case("gdoc_what_does_it_say",
         "What does my 'Resume' Google Doc say about my last job?", "",
         "emi_team_manager",
         category="emi_team",
         notes="gdoc find + selective read → emi_team."),
    Case("gdoc_append_section",
         "Append a new section to my 'Notes' Google Doc titled 'Switchboard Tests'.", "",
         "emi_team_manager",
         category="emi_team",
         notes="gdoc find + edit → emi_team."),

    # ---- personal_admin cross-domain (email + calendar + todo + reminder) ----
    Case("email_and_calendar_peter",
         "Email Peter to confirm Friday 3pm, and create a calendar event for the same time.", "",
         "personal_admin_manager",
         category="personal_admin",
         notes="email + calendar are both personal_admin's domain."),
    Case("find_dentist_to_calendar",
         "Find the dentist email and add the appointment to my calendar.", "",
         "personal_admin_manager",
         category="personal_admin",
         notes="email find + calendar create — personal_admin handles both."),
    Case("cancel_meetings_email_attendees",
         "Cancel my Friday meetings and email the attendees that I won't make it.", "",
         "personal_admin_manager",
         category="personal_admin",
         notes="calendar delete + email send — both personal_admin."),
    Case("snooze_email_set_reminder",
         "Snooze the email from Mark and set a reminder to deal with it Monday.", "",
         "personal_admin_manager",
         category="personal_admin",
         notes="email action + reminder — both personal_admin."),

    # ---- web service-fetch (more variety) ----
    Case("bbc_homepage",
         "Get me the top stories from the BBC homepage.", "",
         "web_manager",
         category="web",
         notes="Public news fetch."),
    Case("github_anthropic_releases",
         "What are the latest releases on GitHub for the 'anthropic' org?", "",
         "web_manager", accept_also=("playwright_manager",),
         category="web",
         notes="Public GitHub data."),
    Case("twitter_trending",
         "Pull the trending topics on Twitter.", "",
         "playwright_manager", accept_also=("web_manager",),
         category="web",
         notes="Twitter blocks scrapers and is auth-walled — likely playwright."),
    Case("stackoverflow_search",
         "Search Stack Overflow for Python pickle protocol bugs.", "",
         "web_manager",
         category="web",
         notes="Public search."),
    Case("anthropic_changelog",
         "Find the official changelog for Anthropic's API.", "",
         "web_manager",
         category="web",
         notes="Public docs page."),

    # ---- bash variants ----
    Case("size_pictures",
         "How big is my Pictures folder?", "",
         "bash_manager",
         category="bash",
         notes="Filesystem size read."),
    Case("open_main_py",
         "Open the file ~/projects/main.py.", "",
         "bash_manager",
         category="bash",
         notes="Read text file."),
    Case("find_logs_today",
         "Find all .log files modified today in my home folder.", "",
         "bash_manager",
         category="bash",
         notes="Filesystem search by pattern."),

    # ---- "ask <X>" / "tell <X>" disambiguation probes ----
    Case("ask_phil_time",
         "Ask Phil what time the meeting is tomorrow.", "",
         "personal_admin_manager", accept_also=("create_dayflow_ticket", "emi_team_manager"),
         category="tricky",
         notes="Phil is not the user → send email; but suffers same ambiguity as ask_katy_pizza."),
    Case("ask_jukka_dinner_3rd",
         "Ask Jukka what he wants for dinner.", "",
         "create_dayflow_ticket",
         category="tricky",
         notes="Jukka IS the user (third-person framing) — user is the source → ticket."),
    Case("tell_susie_late",
         "Tell Susie I'll be late.", "",
         "personal_admin_manager",
         category="tricky",
         notes="Susie is not the user → send email."),
    Case("tell_jukka_dishwasher",
         "Tell Jukka the dishwasher needs servicing.", "",
         "create_dayflow_ticket",
         category="tricky",
         notes="Jukka IS the user → ticket."),
    Case("ask_me_dinner",
         "Ask me what I want for dinner.", "",
         "create_dayflow_ticket",
         category="tricky",
         notes="'me' = the user → ticket."),

    # ---- complex workflows that require emi_team (step OUTSIDE admin domains) ----
    Case("anthropic_ooo_to_calendar",
         "Find the date of the next Anthropic OOO and add it to my calendar.", "",
         "emi_team_manager",
         category="emi_team",
         notes="Web research + calendar — crosses out of personal_admin's domain."),
    Case("flights_paris_to_todo",
         "Look up the cheapest flight to Paris on May 20 and create a todo to book it.", "",
         "emi_team_manager",
         category="emi_team",
         notes="Web + todo — web is outside personal_admin."),
    Case("screenshot_bluesky_to_peter",
         "Take a screenshot of my Bluesky profile and email it to Peter.", "",
         "emi_team_manager",
         category="emi_team",
         notes="Screenshot (pod) + email — crosses domains."),
    Case("github_commits_to_bluesky",
         "Get my GitHub commit count for this week and post it to my Bluesky.", "",
         "emi_team_manager",
         category="emi_team",
         notes="Web fetch + authenticated post = cross-domain."),

    # ---- research+report (NOT ticket, by primary verb) ----
    Case("anthropic_party_date",
         "Find out when the Anthropic Christmas party is and let me know.", "",
         "web_manager", accept_also=("emi_team_manager",),
         category="tricky",
         notes="Research+report — primary verb is 'find', not 'tell'. NOT a ticket."),
    Case("dentist_phone_lookup",
         "Look up the dentist's phone number and tell me.", "",
         "web_manager", accept_also=("emi_team_manager",),
         category="tricky",
         notes="Research+report — primary verb is 'look up'. NOT a ticket."),
)
