name: shared::tool_arguments
class_name: ToolArguments
llm_params:
  llm_provider: "openai"
  engine: "gpt-4.1"
  model_tier: "nano"
  temperature: 0.1

user_context_items:
  - date_time
  - target_name
  - tool_args
  - arguments

system_context_items: []
