name: kg_maintenance::node_data_merger
class_name: Agent
llm_params:
  engine: gpt-5.4-mini
  model_tier: "mini"
  llm_provider: "openai"
allowed_tools: []
except_tools: []
user_context_items:
- existing_node_data
- new_node_data
- entity_level_0
system_context_items: []
type: agent

entity_scan_keys: [new_node_data]
entity_detection_keys:
  - new_node_data
