ai_assistant_questions = [
    "How do you prefer to receive information (e.g., text, audio, visual)?",
    "What are your primary goals for using an AI assistant?",
    "How often do you use AI assistants or digital tools in your daily life?",
    "What tasks would you like the AI assistant to help you with the most?",
    "Do you have any specific preferences for the AI's communication style (e.g., formal, casual)?",
    "How do you like to organize your schedule and to-do lists?",
    "What are your favorite productivity tools or apps?",
    "Do you prefer concise responses or detailed explanations from the AI?",
    "How do you handle reminders and notifications?",
    "What are your preferred methods for learning new information?",
    "Do you have any accessibility needs the AI should be aware of?",
    "What time of day do you find most productive?",
    "How do you prioritize your tasks and responsibilities?",
    "What are your favorite ways to relax and unwind?",
    "Do you prefer proactive suggestions from the AI or respond when prompted?",
    "How do you like to track your personal goals and progress?",
    "What are your favorite topics to discuss or explore?",
    "How important is data privacy to you when interacting with an AI assistant?",
    "Do you prefer the AI to remember past interactions to personalize future responses?",
    "What are your favorite ways to stay motivated?",
    "How do you prefer to receive updates or summaries (e.g., daily, weekly)?",
    "Do you use any smart home devices that the AI assistant should integrate with?",
    "What are your favorite news sources or types of news you follow?",
    "How do you like to handle emails and communications?",
    "What are your favorite entertainment options (e.g., movies, music, books)?",
    "Do you have any dietary preferences or restrictions the AI should consider for meal suggestions?",
    "How do you prefer to manage your finances and budgeting?",
    "What are your favorite fitness activities or routines?",
    "Do you travel frequently, and how can the AI assist with travel planning?",
    "What languages do you speak or would like to learn?",
    "How do you prefer to set and review your personal development goals?",
    "What are your favorite hobbies or creative outlets?",
    "Do you prefer visual aids like charts and graphs when tracking progress?",
    "How do you like to celebrate your achievements and milestones?",
    "What are your preferred methods for stress management?",
    "Do you have any specific health goals the AI can help you track?",
    "How do you like to receive feedback or constructive suggestions?",
    "What are your favorite ways to stay connected with friends and family?",
    "Do you use any specific platforms for social media or networking?",
    "How do you prefer to handle task delegation or collaboration?",
    "What are your favorite sources for educational content?",
    "Do you engage in any volunteer work or community service?",
    "How do you like to document or journal your thoughts and experiences?",
    "What are your preferred methods for tracking and improving sleep quality?",
    "Do you have any specific environmental or sustainability goals?",
    "How do you prefer to explore new interests or hobbies?",
    "What are your favorite ways to challenge yourself intellectually?",
    "Do you use any specific tools for time management (e.g., Pomodoro timers)?",
    "How do you like the AI to assist with personal reflection or mindfulness?",
    "What are your preferred ways to receive motivational quotes or affirmations?",
    "Do you prefer typing or speaking commands to your AI assistant?",
    "How frequently would you like to receive updates or notifications from the AI?",
    "Do you enjoy interactive features like quizzes or games from your AI assistant?",
    "What personal interests should the AI prioritize when suggesting content?",
    "Do you have a preferred tone or language style for the AI to use?",
    "Are there any topics you would like the AI to avoid?",
    "What short-term goals would you like the AI to help you achieve?",
    "How do you measure progress towards your long-term goals?",
    "Would you like the AI to provide reminders and check-ins for your goals?",
    "What new skills are you interested in learning with the AI's assistance?",
    "Do you prefer structured courses or casual learning opportunities?",
    "How does the AI assist you in retaining new information?",
    "Would you like the AI to track your daily water intake or nutrition?",
    "How can the AI assist you in maintaining a balanced lifestyle?",
    "Do you use any fitness trackers that the AI should integrate with?",
    "What genres of music or podcasts do you prefer the AI to recommend?",
    "Would you like the AI to create personalized playlists for you?",
    "How can the AI enhance your leisure time activities?",
]
