questions = [
    "What's your favorite book and why?",
    "What hobbies are you passionate about?",
    "Where did you grow up?",
    "What's your favorite movie of all time?",
    "Do you have any siblings?",
    "What's your favorite type of music?",
    "What do you do for work?",
    "What's a skill you'd like to learn and why?",
    "What's your favorite food?",
    "Do you have any pets?",
    "What's the most memorable place you've traveled to?",
    "What's your favorite way to spend a weekend?",
    "What's one thing you're currently trying to improve about yourself?",
    "Do you prefer coffee or tea?",
    "What's your favorite season and why?",
    "What's a fun fact about you that not many people know?",
    "What's your favorite sport or physical activity?",
    "Do you enjoy cooking? If so, what's your signature dish?",
    "What's the best piece of advice you've ever received?",
    "What's your favorite childhood memory?",
    "Are you a morning person or a night owl?",
    "What's something you've always wanted to try but haven't yet?",
    "What's your favorite TV show right now?",
    "Do you enjoy reading? If so, what's the last book you read?",
    "What's your favorite holiday and how do you celebrate it?",
    "What's the most challenging thing you've ever done?",
    "Do you prefer the beach or the mountains?",
    "What's your favorite way to relax?",
    "What's a goal you're currently working towards?",
    "Do you speak any other languages?",
    "What's your favorite dessert?",
    "What's the last concert you attended?",
    "Do you have a favorite quote or motto?",
    "What's your favorite app on your phone?",
    "What's something you're grateful for today?",
    "Do you enjoy any form of art? Which one?",
    "What's your favorite game, board or video?",
    "What's the best gift you've ever received?",
    "Do you prefer reading books or watching movies?",
    "What's your favorite animal and why?",
    "Have you ever met anyone famous?",
    "What's your favorite way to exercise?",
    "Do you have a favorite city you'd like to visit?",
    "What's your favorite thing about your current job?",
    "What's a habit you're proud of?",
    "Do you enjoy gardening or indoor plants?",
    "What's your favorite beverage?",
    "What's the most interesting documentary you've watched?",
    "Do you prefer texting or talking on the phone?",
    "What's a memorable event from your school days?",
    "What's your favorite type of cuisine?",
    "Do you enjoy any outdoor activities?",
    "What's your favorite thing to do with friends?",
    "What's a project you're currently working on?",
    "Do you have any phobias?",
    "What's your favorite technology gadget?",
    "What's the best vacation you've ever had?",
    "Do you enjoy any form of writing?",
    "What's your favorite time of day?",
    "What's something you've done that you're really proud of?",
    "Do you prefer driving or taking public transportation?",
    "What's your favorite board game or card game?",
    "What's the last new thing you tried?",
    "Do you have a favorite comedian or comedy show?",
    "What's your favorite place to unwind?",
    "Do you believe in luck or fate?",
    "What's your favorite way to give back to the community?",
    "What's the most unusual job you've ever had?",
    "Do you prefer sweet or savory snacks?",
    "What's a language you'd like to learn?",
    "What's your favorite thing about the city you live in?",
    "Do you enjoy attending live events? Which ones?",
    "What's your favorite type of weather?",
    "What's a book that has influenced you greatly?",
    "Do you have any personal traditions?",
    "What's your favorite mode of transportation?",
    "What's something you can't live without?",
    "Do you enjoy any DIY projects?",
    "What's your favorite thing to do on a rainy day?",
    "Do you have a favorite historical period?",
    "What's the best meal you've ever had?",
    "Do you prefer staying in or going out?",
    "What's your favorite thing about your best friend?",
    "Do you enjoy any form of meditation or mindfulness?",
    "What's a talent you have that not many people know about?",
    "What's your favorite thing to do in your free time?",
    "Do you prefer cats or dogs?",
    "What's your favorite way to celebrate your birthday?",
    "Do you have a favorite sports team?",
    "What's something you're looking forward to?",
    "Do you enjoy any form of collecting?",
    "What's your favorite way to stay active?",
    "Do you prefer sunrises or sunsets?",
    "What's a place you've always wanted to live?",
    "Do you enjoy any virtual or augmented reality experiences?",
    "What's your favorite type of art?",
    "Do you have a favorite podcast or radio show?",
    "What's your favorite way to start the day?",
    "Do you enjoy any extreme sports or activities?",
    "What's a cause you're passionate about?",
    "Do you have a favorite family tradition?",
    "What's the most beautiful place you've ever seen?",
    "Do you prefer handwritten letters or digital messages?",
    "What's your favorite thing about yourself?",
]
