name: email_parser
class_name: Agent
action_required: false
llm_params:
  llm_provider: "openai"
  engine: "gpt-5-mini"
  model_tier: "mini"

entity_scan_keys: [agent_input]

system_context_items:
  - resource_email_user_prefs

user_context_items:
  - date_time
  - agent_input
  - entity_summary
  - entity_metadata
