name: kg_query::planner
class_name: Planner
llm_params:
  llm_provider: "openai"
  engine: "gpt-5-mini"
  model_tier: "mini"
  

allowed_tools: [kg_find_edge, kg_describe_node, kg_describe_edge, ask_user, kg_update_node, kg_create_node, kg_create_edge, kg_delete_node, kg_delete_edge]
allowed_nodes: [kg_query::find_nodes, return_control]

user_context_items:
  - date_time
  - task
  - information
  - recent_history
  - checklist
  - action_count

system_context_items:
  - tool_descriptions
  - allowed_nodes
  - task
  - resource_user_data
  - resource_assistant_data



