name: daily_summary::email_analyzer::email_analyze
class_name: Agent
llm_params:
  llm_provider: "openai"
  engine: "gpt-5-mini"
  model_tier: "mini"
  

allowed_tools:
  - get_important_emails
except_tools: []

user_context_items:
  - date_time
  - recent_history

system_context_items:
  - tool_descriptions
















