name: me::query_filter
class_name: Agent
action_required: false
llm_params:
  llm_provider: "openai"
  engine: "gpt-5-mini"
  model_tier: "mini"

allowed_tools: []
except_tools: []
allowed_nodes: []
entity_scan_keys: [task]
entity_card_level: 0

user_context_items:
  - date_time
  - task
  - information

system_context_items: []
