from __future__ import annotations

import uuid
from datetime import datetime
from typing import Any, Dict

from flask import Blueprint, current_app, jsonify, request

from app.assistant.lib.core_tools.slack.slack import SlackTool
from app.routes._security import dev_tools_enabled
from app.assistant.rooms.room_bootstrap import ensure_slack_room, make_slack_room_id
from app.assistant.slack_interface.slack_room_config import (
    get_slack_channel_id,
    get_slack_room_config,
)
from app.assistant.utils.identity_names import (
    get_required_assistant_name,
    resolve_display_name,
)
from app.assistant.utils.logging_config import get_logger

logger = get_logger(__name__)

slack_room_bp = Blueprint("slack_room", __name__)


def _to_bool(value: Any) -> bool:
    raw = str(value or "").strip().lower()
    return raw in {"1", "true", "yes", "y", "on"}


def _resolve_channel_id(payload_channel_id: str, *, use_latest: bool) -> str:
    cid = str(payload_channel_id or "").strip()
    if cid and (cid != "C_SIM_TEST" or not use_latest):
        return cid

    # Fallback: env/config resolver (supports legacy env aliases too).
    resolved = get_slack_channel_id()
    if resolved:
        return resolved

    return ""


def _fetch_latest_slack_user_message(channel_id: str) -> Dict[str, str]:
    """
    Pull the latest non-Emi user message from the real Slack channel.
    Returns a dict with body/sender_name/sender_id/message_ts/thread_ts.
    Raises RuntimeError on failure/no message.
    """
    tool = SlackTool()
    result = tool.handle_get_messages({"channel_id": channel_id, "limit": 100})
    data_list = getattr(result, "data_list", None)
    messages = data_list if isinstance(data_list, list) else []
    if not messages:
        raise RuntimeError("No Slack messages returned.")

    def _ts(msg: Dict[str, Any]) -> float:
        try:
            return float(str(msg.get("ts") or 0))
        except Exception:
            return 0.0

    assistant_name = get_required_assistant_name().strip().lower()
    for m in sorted([x for x in messages if isinstance(x, dict)], key=_ts, reverse=True):
        sender_name = resolve_display_name(
            raw_name=str(m.get("name") or "").strip(),
            role="participant",
            external_id=str(m.get("user_id") or "").strip(),
            prefer_external_id_for_participant=True,
        )
        body = str(m.get("text") or "").strip()
        images = m.get("images") if isinstance(m.get("images"), list) else []
        markers = [f"[emi_image: {p}]" for p in images if isinstance(p, str) and p.strip()]
        composed = "\n".join([body] + markers) if body and markers else (body or "\n".join(markers))
        if not composed:
            continue
        if sender_name.lower() == assistant_name:
            continue
        return {
            "body": composed,
            "sender_name": sender_name,
            "sender_id": str(m.get("user_id") or "").strip(),
            "message_ts": str(m.get("ts") or "").strip(),
            "thread_ts": str(m.get("thread_ts") or "").strip(),
            "image_paths": [p for p in images if isinstance(p, str) and p.strip()],
        }

    raise RuntimeError("No eligible non-Emi Slack user message found.")


@slack_room_bp.route("/slack/room/simulate", methods=["POST"])
def slack_room_simulate():
    """
    Dev-only simulator for Slack inbound messages to room_manager.

    JSON/form payload:
    - channel_id (required)
    - body (required unless use_latest=true)
    - room_id (optional, defaults to "phil")
    - sender_name (optional)
    - sender_id (optional)
    - message_ts (optional; autogenerated if missing)
    - thread_ts (optional)
    - send_reply (optional; default false)
    - use_latest (optional; when true, pull latest real message from Slack channel)
    - history_count (optional; when >0, pull that many recent real Slack messages as context)
    - speaker_name (optional alias for sender_name)
    """
    if not dev_tools_enabled():
        return jsonify({"error": "Not found"}), 404

    payload = request.get_json(silent=True) if request.is_json else None
    payload = payload if isinstance(payload, dict) else request.values

    channel_id = str(payload.get("channel_id") or "").strip()
    body = str(payload.get("body") or "").strip()
    room_id = ""
    sender_id = str(payload.get("sender_id") or "").strip()
    sender_name = resolve_display_name(
        raw_name=str(payload.get("speaker_name") or payload.get("sender_name") or "").strip(),
        role="participant",
        external_id=sender_id,
        prefer_external_id_for_participant=True,
    )
    message_ts = str(payload.get("message_ts") or "").strip() or f"SIM-{uuid.uuid4().hex[:12]}"
    thread_ts = str(payload.get("thread_ts") or "").strip()
    image_paths = payload.get("image_paths")
    image_paths = image_paths if isinstance(image_paths, list) else []
    send_reply = _to_bool(payload.get("send_reply"))
    cfg = get_slack_room_config()
    default_mode = str(cfg.get("message_persistence_mode") or "global_blackboard_only").strip().lower()
    message_persistence_mode = str(payload.get("message_persistence_mode") or default_mode).strip().lower()
    if message_persistence_mode not in {"global_blackboard_only", "global_blackboard_and_unified_log"}:
        return jsonify(
            {
                "error": (
                    "Invalid message_persistence_mode. "
                    "Use 'global_blackboard_only' or 'global_blackboard_and_unified_log'."
                )
            }
        ), 400
    persist_history_raw = payload.get("persist_history")
    if persist_history_raw is None:
        # Simulator defaults to non-persistent to avoid polluting real room memory.
        persist_history = False
    else:
        persist_history = _to_bool(persist_history_raw)
    try:
        history_count = int(payload.get("history_count") or 0)
    except Exception:
        history_count = 0
    if history_count < 0:
        history_count = 0
    if history_count > 100:
        history_count = 100
    use_latest_raw = payload.get("use_latest")
    if use_latest_raw is None:
        # If caller did not specify, default to latest-fetch when body is empty.
        use_latest = not bool(body.strip())
    else:
        use_latest = _to_bool(use_latest_raw)

    channel_id = _resolve_channel_id(channel_id, use_latest=use_latest)

    if use_latest:
        if not channel_id:
            return jsonify(
                {
                    "error": (
                        "Missing channel_id. Provide channel_id in request, or set SLACK_CHANNEL_ID "
                        "(or EMI_SLACK_CHANNEL_ID/SLACK_ROOM_CHANNEL_ID), "
                        "or configure configs/slack_room.json: channel_id."
                    )
                }
            ), 400
        try:
            latest = _fetch_latest_slack_user_message(channel_id)
            body = latest["body"]
            sender_name = latest["sender_name"] or sender_name
            sender_id = latest["sender_id"] or sender_id
            message_ts = latest["message_ts"] or message_ts
            thread_ts = latest["thread_ts"] or thread_ts
            image_paths = latest.get("image_paths") if isinstance(latest.get("image_paths"), list) else image_paths
        except Exception as e:
            logger.error("Slack room simulator latest-fetch error: %s", e)
            logger.debug("slack room simulator latest-fetch error:  %s exception details", e, exc_info=True)
            return jsonify({"error": f"Failed to fetch latest Slack message: {e}"}), 500

    if not body:
        return jsonify({"error": "Missing required field: body (or set use_latest=true)"}), 400
    if not channel_id:
        return jsonify({"error": "Missing required field: channel_id"}), 400
    room_id = make_slack_room_id(channel_id)

    try:
        ensure_slack_room(
            room_id=room_id,
            channel_id=channel_id,
            sender_name=sender_name,
        )
        outcome: Dict[str, Any] = current_app.DI.room_session_manager.handle_slack_inbound(
            channel_id=channel_id,
            body=body,
            room_id=room_id,
            message_ts=message_ts,
            sender_name=sender_name,
            sender_id=sender_id,
            thread_ts=thread_ts,
            image_paths=image_paths,
            send_reply=send_reply,
            persist_to_history=bool(persist_history),
            message_persistence_mode=message_persistence_mode,
            simulated=True,
        )
        return jsonify(
            {
                "status": "ok",
                "simulated": True,
                "mode": "room_manager",
                "request_id": outcome.get("request_id"),
                "room_id": outcome.get("room_id"),
                "inbound": {
                    "channel_id": channel_id,
                    "body": body,
                    "message_ts": message_ts,
                    "thread_ts": thread_ts,
                    "sender_name": sender_name,
                    "sender_id": sender_id,
                    "image_paths_count": len(image_paths),
                    "use_latest": bool(use_latest),
                    "history_count_requested": int(history_count),
                },
                "send_reply_requested": bool(send_reply),
                "persist_history": bool(persist_history),
                "message_persistence_mode": message_persistence_mode,
                "reply_preview": outcome.get("reply_text"),
                "reply_payload": outcome.get("reply_payload"),
                "outbound_status": outcome.get("outbound_status"),
            }
        ), 200
    except Exception as e:
        logger.error("Slack room simulator handler error: %s", e)
        logger.debug("slack room simulator handler error:  %s exception details", e, exc_info=True)
        return jsonify({"error": "Simulation failed"}), 500

