name: daily_summary::planner
class_name: Planner
llm_params:
  llm_provider: "openai"
  engine: "gpt-5-mini"
  model_tier: "mini"

allowed_tools: [get_todo_tasks, get_important_emails, ask_user, notify_user]
except_tools: []
allowed_nodes: [return_control]

user_context_items:
  - date_time
  - task
  - information
  - resource_expected_calendar
  - resource_weather
  - resource_daily_context_generator_output
  - recent_history
  - checklist
  - action_count
  - tool_descriptions

system_context_items:
  - tool_descriptions
