name: dj_orchestrator
class_name: Agent
llm_params:
  llm_provider: "openai"
  engine: "gpt-5.6-luna"
  model_tier: "mini"
  temperature: 0.9

system_context_items:
  - resource_assistant_data
  - resource_music_preferences

user_context_items:
- date_time
- day_of_week
- vibe
- recently_played
- last_played
- provided_songs
- resource_music_preferences
